//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PredictivePolicingApp.GuestGeek_DBService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CrimeTweets", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial struct CrimeTweets : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double latitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string locationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double longitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mentionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime post_datetimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime recieved_datetimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tagsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int tweet_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string twitter_handleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string weatherField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double latitude {
            get {
                return this.latitudeField;
            }
            set {
                if ((this.latitudeField.Equals(value) != true)) {
                    this.latitudeField = value;
                    this.RaisePropertyChanged("latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string location {
            get {
                return this.locationField;
            }
            set {
                if ((object.ReferenceEquals(this.locationField, value) != true)) {
                    this.locationField = value;
                    this.RaisePropertyChanged("location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double longitude {
            get {
                return this.longitudeField;
            }
            set {
                if ((this.longitudeField.Equals(value) != true)) {
                    this.longitudeField = value;
                    this.RaisePropertyChanged("longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mentions {
            get {
                return this.mentionsField;
            }
            set {
                if ((object.ReferenceEquals(this.mentionsField, value) != true)) {
                    this.mentionsField = value;
                    this.RaisePropertyChanged("mentions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime post_datetime {
            get {
                return this.post_datetimeField;
            }
            set {
                if ((this.post_datetimeField.Equals(value) != true)) {
                    this.post_datetimeField = value;
                    this.RaisePropertyChanged("post_datetime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime recieved_datetime {
            get {
                return this.recieved_datetimeField;
            }
            set {
                if ((this.recieved_datetimeField.Equals(value) != true)) {
                    this.recieved_datetimeField = value;
                    this.RaisePropertyChanged("recieved_datetime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tags {
            get {
                return this.tagsField;
            }
            set {
                if ((object.ReferenceEquals(this.tagsField, value) != true)) {
                    this.tagsField = value;
                    this.RaisePropertyChanged("tags");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int tweet_id {
            get {
                return this.tweet_idField;
            }
            set {
                if ((this.tweet_idField.Equals(value) != true)) {
                    this.tweet_idField = value;
                    this.RaisePropertyChanged("tweet_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string twitter_handle {
            get {
                return this.twitter_handleField;
            }
            set {
                if ((object.ReferenceEquals(this.twitter_handleField, value) != true)) {
                    this.twitter_handleField = value;
                    this.RaisePropertyChanged("twitter_handle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string weather {
            get {
                return this.weatherField;
            }
            set {
                if ((object.ReferenceEquals(this.weatherField, value) != true)) {
                    this.weatherField = value;
                    this.RaisePropertyChanged("weather");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SVM", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial struct SVM : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string alphasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string kernalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string labelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string support_vectorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int sv_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int tweet_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string weighted_sumsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string alphas {
            get {
                return this.alphasField;
            }
            set {
                if ((object.ReferenceEquals(this.alphasField, value) != true)) {
                    this.alphasField = value;
                    this.RaisePropertyChanged("alphas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string kernal {
            get {
                return this.kernalField;
            }
            set {
                if ((object.ReferenceEquals(this.kernalField, value) != true)) {
                    this.kernalField = value;
                    this.RaisePropertyChanged("kernal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string label {
            get {
                return this.labelField;
            }
            set {
                if ((object.ReferenceEquals(this.labelField, value) != true)) {
                    this.labelField = value;
                    this.RaisePropertyChanged("label");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string support_vectors {
            get {
                return this.support_vectorsField;
            }
            set {
                if ((object.ReferenceEquals(this.support_vectorsField, value) != true)) {
                    this.support_vectorsField = value;
                    this.RaisePropertyChanged("support_vectors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int sv_id {
            get {
                return this.sv_idField;
            }
            set {
                if ((this.sv_idField.Equals(value) != true)) {
                    this.sv_idField = value;
                    this.RaisePropertyChanged("sv_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int tweet_id {
            get {
                return this.tweet_idField;
            }
            set {
                if ((this.tweet_idField.Equals(value) != true)) {
                    this.tweet_idField = value;
                    this.RaisePropertyChanged("tweet_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string weighted_sums {
            get {
                return this.weighted_sumsField;
            }
            set {
                if ((object.ReferenceEquals(this.weighted_sumsField, value) != true)) {
                    this.weighted_sumsField = value;
                    this.RaisePropertyChanged("weighted_sums");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sentiments", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial struct Sentiments : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string category_primaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string key_phrasesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int sentiment_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double sentiment_totalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int tweet_idField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string category_primary {
            get {
                return this.category_primaryField;
            }
            set {
                if ((object.ReferenceEquals(this.category_primaryField, value) != true)) {
                    this.category_primaryField = value;
                    this.RaisePropertyChanged("category_primary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string key_phrases {
            get {
                return this.key_phrasesField;
            }
            set {
                if ((object.ReferenceEquals(this.key_phrasesField, value) != true)) {
                    this.key_phrasesField = value;
                    this.RaisePropertyChanged("key_phrases");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int sentiment_id {
            get {
                return this.sentiment_idField;
            }
            set {
                if ((this.sentiment_idField.Equals(value) != true)) {
                    this.sentiment_idField = value;
                    this.RaisePropertyChanged("sentiment_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double sentiment_total {
            get {
                return this.sentiment_totalField;
            }
            set {
                if ((this.sentiment_totalField.Equals(value) != true)) {
                    this.sentiment_totalField = value;
                    this.RaisePropertyChanged("sentiment_total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int tweet_id {
            get {
                return this.tweet_idField;
            }
            set {
                if ((this.tweet_idField.Equals(value) != true)) {
                    this.tweet_idField = value;
                    this.RaisePropertyChanged("tweet_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Entities", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial struct Entities : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string category_typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int entity_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double senti_magnitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double senti_salienceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double senti_scoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double sentiment_idField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string category_type {
            get {
                return this.category_typeField;
            }
            set {
                if ((object.ReferenceEquals(this.category_typeField, value) != true)) {
                    this.category_typeField = value;
                    this.RaisePropertyChanged("category_type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int entity_id {
            get {
                return this.entity_idField;
            }
            set {
                if ((this.entity_idField.Equals(value) != true)) {
                    this.entity_idField = value;
                    this.RaisePropertyChanged("entity_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double senti_magnitude {
            get {
                return this.senti_magnitudeField;
            }
            set {
                if ((this.senti_magnitudeField.Equals(value) != true)) {
                    this.senti_magnitudeField = value;
                    this.RaisePropertyChanged("senti_magnitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double senti_salience {
            get {
                return this.senti_salienceField;
            }
            set {
                if ((this.senti_salienceField.Equals(value) != true)) {
                    this.senti_salienceField = value;
                    this.RaisePropertyChanged("senti_salience");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double senti_score {
            get {
                return this.senti_scoreField;
            }
            set {
                if ((this.senti_scoreField.Equals(value) != true)) {
                    this.senti_scoreField = value;
                    this.RaisePropertyChanged("senti_score");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double sentiment_id {
            get {
                return this.sentiment_idField;
            }
            set {
                if ((this.sentiment_idField.Equals(value) != true)) {
                    this.sentiment_idField = value;
                    this.RaisePropertyChanged("sentiment_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GuestGeek_DBService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetData", ReplyAction="http://tempuri.org/IService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetData", ReplyAction="http://tempuri.org/IService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/TestConnection", ReplyAction="http://tempuri.org/IService/TestConnectionResponse")]
        string TestConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/TestConnection", ReplyAction="http://tempuri.org/IService/TestConnectionResponse")]
        System.Threading.Tasks.Task<string> TestConnectionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService/GetDataUsingDataContractResponse")]
        PredictivePolicingApp.GuestGeek_DBService.CompositeType GetDataUsingDataContract(PredictivePolicingApp.GuestGeek_DBService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<PredictivePolicingApp.GuestGeek_DBService.CompositeType> GetDataUsingDataContractAsync(PredictivePolicingApp.GuestGeek_DBService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getCrimeTweets", ReplyAction="http://tempuri.org/IService/getCrimeTweetsResponse")]
        System.Collections.Generic.List<PredictivePolicingApp.GuestGeek_DBService.CrimeTweets> getCrimeTweets();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getCrimeTweets", ReplyAction="http://tempuri.org/IService/getCrimeTweetsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<PredictivePolicingApp.GuestGeek_DBService.CrimeTweets>> getCrimeTweetsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getCrimeTweet", ReplyAction="http://tempuri.org/IService/getCrimeTweetResponse")]
        PredictivePolicingApp.GuestGeek_DBService.CrimeTweets getCrimeTweet(int tweet_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getCrimeTweet", ReplyAction="http://tempuri.org/IService/getCrimeTweetResponse")]
        System.Threading.Tasks.Task<PredictivePolicingApp.GuestGeek_DBService.CrimeTweets> getCrimeTweetAsync(int tweet_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/setCrimeTweet", ReplyAction="http://tempuri.org/IService/setCrimeTweetResponse")]
        int setCrimeTweet(PredictivePolicingApp.GuestGeek_DBService.CrimeTweets crime_tweet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/setCrimeTweet", ReplyAction="http://tempuri.org/IService/setCrimeTweetResponse")]
        System.Threading.Tasks.Task<int> setCrimeTweetAsync(PredictivePolicingApp.GuestGeek_DBService.CrimeTweets crime_tweet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/addCrimeTweet", ReplyAction="http://tempuri.org/IService/addCrimeTweetResponse")]
        int addCrimeTweet(PredictivePolicingApp.GuestGeek_DBService.CrimeTweets crime_tweet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/addCrimeTweet", ReplyAction="http://tempuri.org/IService/addCrimeTweetResponse")]
        System.Threading.Tasks.Task<int> addCrimeTweetAsync(PredictivePolicingApp.GuestGeek_DBService.CrimeTweets crime_tweet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/addCrimeTweets", ReplyAction="http://tempuri.org/IService/addCrimeTweetsResponse")]
        int addCrimeTweets(System.Collections.Generic.List<PredictivePolicingApp.GuestGeek_DBService.CrimeTweets> crime_tweets);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/addCrimeTweets", ReplyAction="http://tempuri.org/IService/addCrimeTweetsResponse")]
        System.Threading.Tasks.Task<int> addCrimeTweetsAsync(System.Collections.Generic.List<PredictivePolicingApp.GuestGeek_DBService.CrimeTweets> crime_tweets);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/deleteCrimeTweet", ReplyAction="http://tempuri.org/IService/deleteCrimeTweetResponse")]
        int deleteCrimeTweet(int tweet_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/deleteCrimeTweet", ReplyAction="http://tempuri.org/IService/deleteCrimeTweetResponse")]
        System.Threading.Tasks.Task<int> deleteCrimeTweetAsync(int tweet_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getSVMs", ReplyAction="http://tempuri.org/IService/getSVMsResponse")]
        System.Collections.Generic.List<PredictivePolicingApp.GuestGeek_DBService.SVM> getSVMs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getSVMs", ReplyAction="http://tempuri.org/IService/getSVMsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<PredictivePolicingApp.GuestGeek_DBService.SVM>> getSVMsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getSVM", ReplyAction="http://tempuri.org/IService/getSVMResponse")]
        PredictivePolicingApp.GuestGeek_DBService.SVM getSVM(int sv_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getSVM", ReplyAction="http://tempuri.org/IService/getSVMResponse")]
        System.Threading.Tasks.Task<PredictivePolicingApp.GuestGeek_DBService.SVM> getSVMAsync(int sv_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/setSVM", ReplyAction="http://tempuri.org/IService/setSVMResponse")]
        int setSVM(PredictivePolicingApp.GuestGeek_DBService.SVM svm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/setSVM", ReplyAction="http://tempuri.org/IService/setSVMResponse")]
        System.Threading.Tasks.Task<int> setSVMAsync(PredictivePolicingApp.GuestGeek_DBService.SVM svm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/addSVM", ReplyAction="http://tempuri.org/IService/addSVMResponse")]
        int addSVM(PredictivePolicingApp.GuestGeek_DBService.SVM svm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/addSVM", ReplyAction="http://tempuri.org/IService/addSVMResponse")]
        System.Threading.Tasks.Task<int> addSVMAsync(PredictivePolicingApp.GuestGeek_DBService.SVM svm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/deleteSVM", ReplyAction="http://tempuri.org/IService/deleteSVMResponse")]
        int deleteSVM(int sv_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/deleteSVM", ReplyAction="http://tempuri.org/IService/deleteSVMResponse")]
        System.Threading.Tasks.Task<int> deleteSVMAsync(int sv_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getSentiments", ReplyAction="http://tempuri.org/IService/getSentimentsResponse")]
        System.Collections.Generic.List<PredictivePolicingApp.GuestGeek_DBService.Sentiments> getSentiments();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getSentiments", ReplyAction="http://tempuri.org/IService/getSentimentsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<PredictivePolicingApp.GuestGeek_DBService.Sentiments>> getSentimentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getSentiment", ReplyAction="http://tempuri.org/IService/getSentimentResponse")]
        PredictivePolicingApp.GuestGeek_DBService.Sentiments getSentiment(int sentiment_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getSentiment", ReplyAction="http://tempuri.org/IService/getSentimentResponse")]
        System.Threading.Tasks.Task<PredictivePolicingApp.GuestGeek_DBService.Sentiments> getSentimentAsync(int sentiment_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/setSentiment", ReplyAction="http://tempuri.org/IService/setSentimentResponse")]
        int setSentiment(PredictivePolicingApp.GuestGeek_DBService.Sentiments sentiment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/setSentiment", ReplyAction="http://tempuri.org/IService/setSentimentResponse")]
        System.Threading.Tasks.Task<int> setSentimentAsync(PredictivePolicingApp.GuestGeek_DBService.Sentiments sentiment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/addSentiment", ReplyAction="http://tempuri.org/IService/addSentimentResponse")]
        int addSentiment(PredictivePolicingApp.GuestGeek_DBService.Sentiments sentiment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/addSentiment", ReplyAction="http://tempuri.org/IService/addSentimentResponse")]
        System.Threading.Tasks.Task<int> addSentimentAsync(PredictivePolicingApp.GuestGeek_DBService.Sentiments sentiment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/deleteSentiment", ReplyAction="http://tempuri.org/IService/deleteSentimentResponse")]
        int deleteSentiment(int sentiment_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/deleteSentiment", ReplyAction="http://tempuri.org/IService/deleteSentimentResponse")]
        System.Threading.Tasks.Task<int> deleteSentimentAsync(int sentiment_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getEntities", ReplyAction="http://tempuri.org/IService/getEntitiesResponse")]
        System.Collections.Generic.List<PredictivePolicingApp.GuestGeek_DBService.Entities> getEntities();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getEntities", ReplyAction="http://tempuri.org/IService/getEntitiesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<PredictivePolicingApp.GuestGeek_DBService.Entities>> getEntitiesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getEntity", ReplyAction="http://tempuri.org/IService/getEntityResponse")]
        PredictivePolicingApp.GuestGeek_DBService.Entities getEntity(int entity_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getEntity", ReplyAction="http://tempuri.org/IService/getEntityResponse")]
        System.Threading.Tasks.Task<PredictivePolicingApp.GuestGeek_DBService.Entities> getEntityAsync(int entity_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/setEntity", ReplyAction="http://tempuri.org/IService/setEntityResponse")]
        int setEntity(PredictivePolicingApp.GuestGeek_DBService.Entities entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/setEntity", ReplyAction="http://tempuri.org/IService/setEntityResponse")]
        System.Threading.Tasks.Task<int> setEntityAsync(PredictivePolicingApp.GuestGeek_DBService.Entities entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/addEntity", ReplyAction="http://tempuri.org/IService/addEntityResponse")]
        int addEntity(PredictivePolicingApp.GuestGeek_DBService.Entities entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/addEntity", ReplyAction="http://tempuri.org/IService/addEntityResponse")]
        System.Threading.Tasks.Task<int> addEntityAsync(PredictivePolicingApp.GuestGeek_DBService.Entities entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/deleteEntity", ReplyAction="http://tempuri.org/IService/deleteEntityResponse")]
        int deleteEntity(int entity_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/deleteEntity", ReplyAction="http://tempuri.org/IService/deleteEntityResponse")]
        System.Threading.Tasks.Task<int> deleteEntityAsync(int entity_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/refreshDBData", ReplyAction="http://tempuri.org/IService/refreshDBDataResponse")]
        System.Collections.Generic.List<string> refreshDBData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/refreshDBData", ReplyAction="http://tempuri.org/IService/refreshDBDataResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> refreshDBDataAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : PredictivePolicingApp.GuestGeek_DBService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<PredictivePolicingApp.GuestGeek_DBService.IService>, PredictivePolicingApp.GuestGeek_DBService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public string TestConnection() {
            return base.Channel.TestConnection();
        }
        
        public System.Threading.Tasks.Task<string> TestConnectionAsync() {
            return base.Channel.TestConnectionAsync();
        }
        
        public PredictivePolicingApp.GuestGeek_DBService.CompositeType GetDataUsingDataContract(PredictivePolicingApp.GuestGeek_DBService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<PredictivePolicingApp.GuestGeek_DBService.CompositeType> GetDataUsingDataContractAsync(PredictivePolicingApp.GuestGeek_DBService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public System.Collections.Generic.List<PredictivePolicingApp.GuestGeek_DBService.CrimeTweets> getCrimeTweets() {
            return base.Channel.getCrimeTweets();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<PredictivePolicingApp.GuestGeek_DBService.CrimeTweets>> getCrimeTweetsAsync() {
            return base.Channel.getCrimeTweetsAsync();
        }
        
        public PredictivePolicingApp.GuestGeek_DBService.CrimeTweets getCrimeTweet(int tweet_id) {
            return base.Channel.getCrimeTweet(tweet_id);
        }
        
        public System.Threading.Tasks.Task<PredictivePolicingApp.GuestGeek_DBService.CrimeTweets> getCrimeTweetAsync(int tweet_id) {
            return base.Channel.getCrimeTweetAsync(tweet_id);
        }
        
        public int setCrimeTweet(PredictivePolicingApp.GuestGeek_DBService.CrimeTweets crime_tweet) {
            return base.Channel.setCrimeTweet(crime_tweet);
        }
        
        public System.Threading.Tasks.Task<int> setCrimeTweetAsync(PredictivePolicingApp.GuestGeek_DBService.CrimeTweets crime_tweet) {
            return base.Channel.setCrimeTweetAsync(crime_tweet);
        }
        
        public int addCrimeTweet(PredictivePolicingApp.GuestGeek_DBService.CrimeTweets crime_tweet) {
            return base.Channel.addCrimeTweet(crime_tweet);
        }
        
        public System.Threading.Tasks.Task<int> addCrimeTweetAsync(PredictivePolicingApp.GuestGeek_DBService.CrimeTweets crime_tweet) {
            return base.Channel.addCrimeTweetAsync(crime_tweet);
        }
        
        public int addCrimeTweets(System.Collections.Generic.List<PredictivePolicingApp.GuestGeek_DBService.CrimeTweets> crime_tweets) {
            return base.Channel.addCrimeTweets(crime_tweets);
        }
        
        public System.Threading.Tasks.Task<int> addCrimeTweetsAsync(System.Collections.Generic.List<PredictivePolicingApp.GuestGeek_DBService.CrimeTweets> crime_tweets) {
            return base.Channel.addCrimeTweetsAsync(crime_tweets);
        }
        
        public int deleteCrimeTweet(int tweet_id) {
            return base.Channel.deleteCrimeTweet(tweet_id);
        }
        
        public System.Threading.Tasks.Task<int> deleteCrimeTweetAsync(int tweet_id) {
            return base.Channel.deleteCrimeTweetAsync(tweet_id);
        }
        
        public System.Collections.Generic.List<PredictivePolicingApp.GuestGeek_DBService.SVM> getSVMs() {
            return base.Channel.getSVMs();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<PredictivePolicingApp.GuestGeek_DBService.SVM>> getSVMsAsync() {
            return base.Channel.getSVMsAsync();
        }
        
        public PredictivePolicingApp.GuestGeek_DBService.SVM getSVM(int sv_id) {
            return base.Channel.getSVM(sv_id);
        }
        
        public System.Threading.Tasks.Task<PredictivePolicingApp.GuestGeek_DBService.SVM> getSVMAsync(int sv_id) {
            return base.Channel.getSVMAsync(sv_id);
        }
        
        public int setSVM(PredictivePolicingApp.GuestGeek_DBService.SVM svm) {
            return base.Channel.setSVM(svm);
        }
        
        public System.Threading.Tasks.Task<int> setSVMAsync(PredictivePolicingApp.GuestGeek_DBService.SVM svm) {
            return base.Channel.setSVMAsync(svm);
        }
        
        public int addSVM(PredictivePolicingApp.GuestGeek_DBService.SVM svm) {
            return base.Channel.addSVM(svm);
        }
        
        public System.Threading.Tasks.Task<int> addSVMAsync(PredictivePolicingApp.GuestGeek_DBService.SVM svm) {
            return base.Channel.addSVMAsync(svm);
        }
        
        public int deleteSVM(int sv_id) {
            return base.Channel.deleteSVM(sv_id);
        }
        
        public System.Threading.Tasks.Task<int> deleteSVMAsync(int sv_id) {
            return base.Channel.deleteSVMAsync(sv_id);
        }
        
        public System.Collections.Generic.List<PredictivePolicingApp.GuestGeek_DBService.Sentiments> getSentiments() {
            return base.Channel.getSentiments();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<PredictivePolicingApp.GuestGeek_DBService.Sentiments>> getSentimentsAsync() {
            return base.Channel.getSentimentsAsync();
        }
        
        public PredictivePolicingApp.GuestGeek_DBService.Sentiments getSentiment(int sentiment_id) {
            return base.Channel.getSentiment(sentiment_id);
        }
        
        public System.Threading.Tasks.Task<PredictivePolicingApp.GuestGeek_DBService.Sentiments> getSentimentAsync(int sentiment_id) {
            return base.Channel.getSentimentAsync(sentiment_id);
        }
        
        public int setSentiment(PredictivePolicingApp.GuestGeek_DBService.Sentiments sentiment) {
            return base.Channel.setSentiment(sentiment);
        }
        
        public System.Threading.Tasks.Task<int> setSentimentAsync(PredictivePolicingApp.GuestGeek_DBService.Sentiments sentiment) {
            return base.Channel.setSentimentAsync(sentiment);
        }
        
        public int addSentiment(PredictivePolicingApp.GuestGeek_DBService.Sentiments sentiment) {
            return base.Channel.addSentiment(sentiment);
        }
        
        public System.Threading.Tasks.Task<int> addSentimentAsync(PredictivePolicingApp.GuestGeek_DBService.Sentiments sentiment) {
            return base.Channel.addSentimentAsync(sentiment);
        }
        
        public int deleteSentiment(int sentiment_id) {
            return base.Channel.deleteSentiment(sentiment_id);
        }
        
        public System.Threading.Tasks.Task<int> deleteSentimentAsync(int sentiment_id) {
            return base.Channel.deleteSentimentAsync(sentiment_id);
        }
        
        public System.Collections.Generic.List<PredictivePolicingApp.GuestGeek_DBService.Entities> getEntities() {
            return base.Channel.getEntities();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<PredictivePolicingApp.GuestGeek_DBService.Entities>> getEntitiesAsync() {
            return base.Channel.getEntitiesAsync();
        }
        
        public PredictivePolicingApp.GuestGeek_DBService.Entities getEntity(int entity_id) {
            return base.Channel.getEntity(entity_id);
        }
        
        public System.Threading.Tasks.Task<PredictivePolicingApp.GuestGeek_DBService.Entities> getEntityAsync(int entity_id) {
            return base.Channel.getEntityAsync(entity_id);
        }
        
        public int setEntity(PredictivePolicingApp.GuestGeek_DBService.Entities entity) {
            return base.Channel.setEntity(entity);
        }
        
        public System.Threading.Tasks.Task<int> setEntityAsync(PredictivePolicingApp.GuestGeek_DBService.Entities entity) {
            return base.Channel.setEntityAsync(entity);
        }
        
        public int addEntity(PredictivePolicingApp.GuestGeek_DBService.Entities entity) {
            return base.Channel.addEntity(entity);
        }
        
        public System.Threading.Tasks.Task<int> addEntityAsync(PredictivePolicingApp.GuestGeek_DBService.Entities entity) {
            return base.Channel.addEntityAsync(entity);
        }
        
        public int deleteEntity(int entity_id) {
            return base.Channel.deleteEntity(entity_id);
        }
        
        public System.Threading.Tasks.Task<int> deleteEntityAsync(int entity_id) {
            return base.Channel.deleteEntityAsync(entity_id);
        }
        
        public System.Collections.Generic.List<string> refreshDBData() {
            return base.Channel.refreshDBData();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> refreshDBDataAsync() {
            return base.Channel.refreshDBDataAsync();
        }
    }
}
